### ISSUE TITLE
Question about changes

### ISSUE THREAD

**Issue by jamesjryan** [Tundergit/waifupilot#1]
Hi there - came across your repo from your YouTube videos. 

I've got a 2018 Kia Stinger GT2 AWD w/ a Comma Two and it seems to work great out of the box, with very limited use so far.

I can see you've made a handful of changes on your `kia-release2` branch, mostly UI stuff, but notice some steering changes.

Just curious what the motivation for the changes were and what effects you've noticed - specifically with the steering.

Have you found a way to engage openpilot from 0mph? This is probably my only frustration at the moment.

Sorry for the weird issue - nothing wrong with your code, just this was the only way to contact you.

**Comment by Tundergit** [comment]
Mechanically there appears to be at least two different racks present in Stingers. PID tuning (what comma official is using) does not work in my Stinger (2021 GT Limited AWD.) INDI tuning works so good it's criminal. Basically, if your out of the box experience is super ping pongy and jerky, try this. Thanks for posting, this is good info to share!
